steps:
# Step 1: Restore NuGet packages
- name: 'mcr.microsoft.com/dotnet/framework/sdk:4.8'
  args: ['nuget', 'restore', 'PromptOptimizer.sln']
  
# Step 2: Build solution in Release mode
- name: 'mcr.microsoft.com/dotnet/framework/sdk:4.8'
  args: ['msbuild', 'PromptOptimizer.sln', '/p:Configuration=Release', '/p:Platform=x64']

# Step 3: Copy artifacts to build output
- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', '-r', 'bin/Release', '/workspace/output']

# Artifacts section - defines what to upload
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-builds'
    paths: 
      - 'bin/Release/PromptOptimizer.exe'

# Images section (optional)
images: []

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout - 30 minutes
timeout: 1800s
