steps:
# Step 1: Restore NuGet packages
- name: 'mcr.microsoft.com/dotnet/sdk:7.0'
  args: ['nuget', 'restore', 'PromptOptimizer.sln']
  env:
    - 'DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false'
  
# Step 2: Build solution in Release mode
- name: 'mcr.microsoft.com/dotnet/sdk:7.0'
  args: ['msbuild', 'PromptOptimizer.sln', '/p:Configuration=Release', '/p:Platform=x64']
  env:
    - 'DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false'

# Step 3: Copy EXE to artifacts location
- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', 'bin/Release/PromptOptimizer.exe', 'gs://${PROJECT_ID}-builds/PromptOptimizer.exe']

# Artifacts section - defines what to upload
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-builds'
    paths: 
      - 'bin/Release/PromptOptimizer.exe'

# Images section (optional)
images: []

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout - 30 minutes
timeout: 1800s
