steps:
  # Step 1: Restore NuGet packages
  - name: 'mcr.microsoft.com/windows/servercore:ltsc2019'
    entrypoint: powershell
    args:
      - '-Command'
      - |
        cd PromptOptimizer
        nuget restore
  
  # Step 2: Build the project (Release)
  - name: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'
    entrypoint: powershell
    args:
      - '-Command'
      - |
        cd PromptOptimizer
        msbuild PromptOptimizer.csproj /p:Configuration=Release /p:Platform=x64
  
  # Step 3: Run ILMerge to create portable .exe
  - name: 'mcr.microsoft.com/windows/servercore:ltsc2019'
    entrypoint: powershell
    args:
      - '-Command'
      - |
        cd PromptOptimizer
        ilmerge /out:PromptOptimizer.exe `
          bin/Release/PromptOptimizer.exe `
          bin/Release/Newtonsoft.Json.dll `
          bin/Release/EntityFramework.dll `
          bin/Release/System.Data.SQLite.dll `
          bin/Release/log4net.dll `/t:winexe
  
  # Step 4: Upload to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'PromptOptimizer/bin/Release/PromptOptimizer.exe'
      - 'gs://${PROJECT_ID}-builds/PromptOptimizer.exe'

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-builds'
    paths:
      - 'PromptOptimizer.exe'

images:
  - 'gcr.io/$PROJECT_ID/prompt-optimizer:latest'
