steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    args: ['dotnet', 'restore', 'PromptOptimizer.sln']

  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    args: ['dotnet', 'build', 'PromptOptimizer.sln', '-c', 'Release']

artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-builds'
    paths:
      - 'bin/Release/PromptOptimizer.exe'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
