steps:
# Step 1: Restore NuGet packages using dotnet CLI
- name: 'mcr.microsoft.com/dotnet/sdk:7.0'
  args: ['dotnet', 'restore', 'PromptOptimizer.sln']
  env:
    - 'DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false'
  
# Step 2: Build solution in Release mode using dotnet msbuild
- name: 'mcr.microsoft.com/dotnet/sdk:7.0'
  args: ['dotnet', 'msbuild', 'PromptOptimizer.sln', '/p:Configuration=Release', '/p:Platform=x64']
  env:
    - 'DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false'

# Artifacts section - defines what to upload
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-builds'
    paths: 
      - 'bin/Release/PromptOptimizer.exe'

# Images section (optional)
images: []

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout - 30 minutes
timeout: 1800s
